name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make

    - name: Add testing library
      run: brew install check

    - name: Build tests
      run: make test

    - name: Run tests
      run: ./oko_test
