name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [macos-10.5, macos-11, macos12]

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
